version: 0.0
os: linux
files:
  - source: /
    destination: /var/javecs/calc
hooks:
  BeforeInstall:
    - location: scripts/before_install
      runas: root
  AfterInstall:
    - location: scripts/install_server
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
